### ISSUE TITLE
[Minor] Readability of addresses

### ISSUE THREAD

**Issue by johnyunjr** [YumMe/YumMe#43]
There are spaces missing between address information for most/all of the addresses pulled. Easy fix, but worth mentioning:

![123](https://cloud.githubusercontent.com/assets/14932301/26802947/4f00e802-49f7-11e7-828d-588e63e9ffc5.PNG)

**Comment by greycabb** [comment]
Ah we didn't catch this! Thanks for mentioning, will be fixed with next patch

**Comment by greycabb** [comment]
Fixed in master!
